/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EnderecosRouteImport } from './routes/enderecos'
import { Route as FuncionamentoRouteImport } from './routes/funcionamento'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as ResgatesRouteImport } from './routes/resgates'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDashboardAuditoriaRouteImport } from './routes/admin.dashboard.auditoria'
import { Route as AdminDashboardCardapioRouteImport } from './routes/admin.dashboard.cardapio'
import { Route as AdminDashboardCategoriasRouteImport } from './routes/admin.dashboard.categorias'
import { Route as AdminDashboardClientesRouteImport } from './routes/admin.dashboard.clientes'
import { Route as AdminDashboardConfiguracoesRouteImport } from './routes/admin.dashboard.configuracoes'
import { Route as AdminDashboardCuponsRouteImport } from './routes/admin.dashboard.cupons'
import { Route as AdminDashboardEntregasRouteImport } from './routes/admin.dashboard.entregas'
import { Route as AdminDashboardFinanceiroRouteImport } from './routes/admin.dashboard.financeiro'
import { Route as AdminDashboardGatewaysRouteImport } from './routes/admin.dashboard.gateways'
import { Route as AdminDashboardHorariosRouteImport } from './routes/admin.dashboard.horarios'
import { Route as AdminDashboardLojaPremiosRouteImport } from './routes/admin.dashboard.loja-premios'
import { Route as AdminDashboardPagamentosRouteImport } from './routes/admin.dashboard.pagamentos'
import { Route as AdminDashboardPedidosRouteImport } from './routes/admin.dashboard.pedidos'
import { Route as AdminDashboardProdutosRouteImport } from './routes/admin.dashboard.produtos'
import { Route as AdminDashboardResgatesRouteImport } from './routes/admin.dashboard.resgates'
import { Route as AdminDashboardVisaoRouteImport } from './routes/admin.dashboard.visao'
import { Route as AdminDashboardWhatsappRouteImport } from './routes/admin.dashboard.whatsapp'
import { Route as AdminDashboardFinanceiroDreRouteImport } from './routes/admin.dashboard.financeiro.dre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecosRoute = EnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionamentoRoute = FuncionamentoRouteImport.update({
  id: '/funcionamento',
  path: '/funcionamento',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResgatesRoute = ResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardAuditoriaRoute = AdminDashboardAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardCardapioRoute = AdminDashboardCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardCategoriasRoute =
  AdminDashboardCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardClientesRoute = AdminDashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardConfiguracoesRoute =
  AdminDashboardConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCuponsRoute = AdminDashboardCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardEntregasRoute = AdminDashboardEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardFinanceiroRoute =
  AdminDashboardFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardGatewaysRoute = AdminDashboardGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardHorariosRoute = AdminDashboardHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardLojaPremiosRoute =
  AdminDashboardLojaPremiosRouteImport.update({
    id: '/loja-premios',
    path: '/loja-premios',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPagamentosRoute =
  AdminDashboardPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardPedidosRoute = AdminDashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardProdutosRoute = AdminDashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardResgatesRoute = AdminDashboardResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardVisaoRoute = AdminDashboardVisaoRouteImport.update({
  id: '/visao',
  path: '/visao',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardWhatsappRoute = AdminDashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardFinanceiroDreRoute =
  AdminDashboardFinanceiroDreRouteImport.update({
    id: '/dre',
    path: '/dre',
    getParentRoute: () => AdminDashboardFinanceiroRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/enderecos': typeof EnderecosRoute
  '/funcionamento': typeof FuncionamentoRoute
  '/historico': typeof HistoricoRoute
  '/loja': typeof LojaRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreio': typeof RastreioRoute
  '/resgates': typeof ResgatesRoute
  '/termos': typeof TermosRoute
  '/transacoes': typeof TransacoesRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/auditoria': typeof AdminDashboardAuditoriaRoute
  '/admin/dashboard/cardapio': typeof AdminDashboardCardapioRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/clientes': typeof AdminDashboardClientesRoute
  '/admin/dashboard/configuracoes': typeof AdminDashboardConfiguracoesRoute
  '/admin/dashboard/cupons': typeof AdminDashboardCuponsRoute
  '/admin/dashboard/entregas': typeof AdminDashboardEntregasRoute
  '/admin/dashboard/financeiro': typeof AdminDashboardFinanceiroRouteWithChildren
  '/admin/dashboard/gateways': typeof AdminDashboardGatewaysRoute
  '/admin/dashboard/horarios': typeof AdminDashboardHorariosRoute
  '/admin/dashboard/loja-premios': typeof AdminDashboardLojaPremiosRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
  '/admin/dashboard/produtos': typeof AdminDashboardProdutosRoute
  '/admin/dashboard/resgates': typeof AdminDashboardResgatesRoute
  '/admin/dashboard/visao': typeof AdminDashboardVisaoRoute
  '/admin/dashboard/whatsapp': typeof AdminDashboardWhatsappRoute
  '/admin/dashboard/financeiro/dre': typeof AdminDashboardFinanceiroDreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/enderecos': typeof EnderecosRoute
  '/funcionamento': typeof FuncionamentoRoute
  '/historico': typeof HistoricoRoute
  '/loja': typeof LojaRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreio': typeof RastreioRoute
  '/resgates': typeof ResgatesRoute
  '/termos': typeof TermosRoute
  '/transacoes': typeof TransacoesRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard/auditoria': typeof AdminDashboardAuditoriaRoute
  '/admin/dashboard/cardapio': typeof AdminDashboardCardapioRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/clientes': typeof AdminDashboardClientesRoute
  '/admin/dashboard/configuracoes': typeof AdminDashboardConfiguracoesRoute
  '/admin/dashboard/cupons': typeof AdminDashboardCuponsRoute
  '/admin/dashboard/entregas': typeof AdminDashboardEntregasRoute
  '/admin/dashboard/financeiro': typeof AdminDashboardFinanceiroRouteWithChildren
  '/admin/dashboard/gateways': typeof AdminDashboardGatewaysRoute
  '/admin/dashboard/horarios': typeof AdminDashboardHorariosRoute
  '/admin/dashboard/loja-premios': typeof AdminDashboardLojaPremiosRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
  '/admin/dashboard/produtos': typeof AdminDashboardProdutosRoute
  '/admin/dashboard/resgates': typeof AdminDashboardResgatesRoute
  '/admin/dashboard/visao': typeof AdminDashboardVisaoRoute
  '/admin/dashboard/whatsapp': typeof AdminDashboardWhatsappRoute
  '/admin/dashboard/financeiro/dre': typeof AdminDashboardFinanceiroDreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/enderecos': typeof EnderecosRoute
  '/funcionamento': typeof FuncionamentoRoute
  '/historico': typeof HistoricoRoute
  '/loja': typeof LojaRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreio': typeof RastreioRoute
  '/resgates': typeof ResgatesRoute
  '/termos': typeof TermosRoute
  '/transacoes': typeof TransacoesRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/auditoria': typeof AdminDashboardAuditoriaRoute
  '/admin/dashboard/cardapio': typeof AdminDashboardCardapioRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/clientes': typeof AdminDashboardClientesRoute
  '/admin/dashboard/configuracoes': typeof AdminDashboardConfiguracoesRoute
  '/admin/dashboard/cupons': typeof AdminDashboardCuponsRoute
  '/admin/dashboard/entregas': typeof AdminDashboardEntregasRoute
  '/admin/dashboard/financeiro': typeof AdminDashboardFinanceiroRouteWithChildren
  '/admin/dashboard/gateways': typeof AdminDashboardGatewaysRoute
  '/admin/dashboard/horarios': typeof AdminDashboardHorariosRoute
  '/admin/dashboard/loja-premios': typeof AdminDashboardLojaPremiosRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
  '/admin/dashboard/produtos': typeof AdminDashboardProdutosRoute
  '/admin/dashboard/resgates': typeof AdminDashboardResgatesRoute
  '/admin/dashboard/visao': typeof AdminDashboardVisaoRoute
  '/admin/dashboard/whatsapp': typeof AdminDashboardWhatsappRoute
  '/admin/dashboard/financeiro/dre': typeof AdminDashboardFinanceiroDreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/enderecos'
    | '/funcionamento'
    | '/historico'
    | '/loja'
    | '/perfil'
    | '/privacidade'
    | '/rastreio'
    | '/resgates'
    | '/termos'
    | '/transacoes'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/auditoria'
    | '/admin/dashboard/cardapio'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/clientes'
    | '/admin/dashboard/configuracoes'
    | '/admin/dashboard/cupons'
    | '/admin/dashboard/entregas'
    | '/admin/dashboard/financeiro'
    | '/admin/dashboard/gateways'
    | '/admin/dashboard/horarios'
    | '/admin/dashboard/loja-premios'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
    | '/admin/dashboard/produtos'
    | '/admin/dashboard/resgates'
    | '/admin/dashboard/visao'
    | '/admin/dashboard/whatsapp'
    | '/admin/dashboard/financeiro/dre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/enderecos'
    | '/funcionamento'
    | '/historico'
    | '/loja'
    | '/perfil'
    | '/privacidade'
    | '/rastreio'
    | '/resgates'
    | '/termos'
    | '/transacoes'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/dashboard/auditoria'
    | '/admin/dashboard/cardapio'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/clientes'
    | '/admin/dashboard/configuracoes'
    | '/admin/dashboard/cupons'
    | '/admin/dashboard/entregas'
    | '/admin/dashboard/financeiro'
    | '/admin/dashboard/gateways'
    | '/admin/dashboard/horarios'
    | '/admin/dashboard/loja-premios'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
    | '/admin/dashboard/produtos'
    | '/admin/dashboard/resgates'
    | '/admin/dashboard/visao'
    | '/admin/dashboard/whatsapp'
    | '/admin/dashboard/financeiro/dre'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/enderecos'
    | '/funcionamento'
    | '/historico'
    | '/loja'
    | '/perfil'
    | '/privacidade'
    | '/rastreio'
    | '/resgates'
    | '/termos'
    | '/transacoes'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/auditoria'
    | '/admin/dashboard/cardapio'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/clientes'
    | '/admin/dashboard/configuracoes'
    | '/admin/dashboard/cupons'
    | '/admin/dashboard/entregas'
    | '/admin/dashboard/financeiro'
    | '/admin/dashboard/gateways'
    | '/admin/dashboard/horarios'
    | '/admin/dashboard/loja-premios'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
    | '/admin/dashboard/produtos'
    | '/admin/dashboard/resgates'
    | '/admin/dashboard/visao'
    | '/admin/dashboard/whatsapp'
    | '/admin/dashboard/financeiro/dre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EnderecosRoute: typeof EnderecosRoute
  FuncionamentoRoute: typeof FuncionamentoRoute
  HistoricoRoute: typeof HistoricoRoute
  LojaRoute: typeof LojaRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RastreioRoute: typeof RastreioRoute
  ResgatesRoute: typeof ResgatesRoute
  TermosRoute: typeof TermosRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecos': {
      id: '/enderecos'
      path: '/enderecos'
      fullPath: '/enderecos'
      preLoaderRoute: typeof EnderecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionamento': {
      id: '/funcionamento'
      path: '/funcionamento'
      fullPath: '/funcionamento'
      preLoaderRoute: typeof FuncionamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resgates': {
      id: '/resgates'
      path: '/resgates'
      fullPath: '/resgates'
      preLoaderRoute: typeof ResgatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/auditoria': {
      id: '/admin/dashboard/auditoria'
      path: '/auditoria'
      fullPath: '/admin/dashboard/auditoria'
      preLoaderRoute: typeof AdminDashboardAuditoriaRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/cardapio': {
      id: '/admin/dashboard/cardapio'
      path: '/cardapio'
      fullPath: '/admin/dashboard/cardapio'
      preLoaderRoute: typeof AdminDashboardCardapioRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/categorias': {
      id: '/admin/dashboard/categorias'
      path: '/categorias'
      fullPath: '/admin/dashboard/categorias'
      preLoaderRoute: typeof AdminDashboardCategoriasRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/clientes': {
      id: '/admin/dashboard/clientes'
      path: '/clientes'
      fullPath: '/admin/dashboard/clientes'
      preLoaderRoute: typeof AdminDashboardClientesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/configuracoes': {
      id: '/admin/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/dashboard/configuracoes'
      preLoaderRoute: typeof AdminDashboardConfiguracoesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/cupons': {
      id: '/admin/dashboard/cupons'
      path: '/cupons'
      fullPath: '/admin/dashboard/cupons'
      preLoaderRoute: typeof AdminDashboardCuponsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/entregas': {
      id: '/admin/dashboard/entregas'
      path: '/entregas'
      fullPath: '/admin/dashboard/entregas'
      preLoaderRoute: typeof AdminDashboardEntregasRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/financeiro': {
      id: '/admin/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/admin/dashboard/financeiro'
      preLoaderRoute: typeof AdminDashboardFinanceiroRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/gateways': {
      id: '/admin/dashboard/gateways'
      path: '/gateways'
      fullPath: '/admin/dashboard/gateways'
      preLoaderRoute: typeof AdminDashboardGatewaysRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/horarios': {
      id: '/admin/dashboard/horarios'
      path: '/horarios'
      fullPath: '/admin/dashboard/horarios'
      preLoaderRoute: typeof AdminDashboardHorariosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/loja-premios': {
      id: '/admin/dashboard/loja-premios'
      path: '/loja-premios'
      fullPath: '/admin/dashboard/loja-premios'
      preLoaderRoute: typeof AdminDashboardLojaPremiosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/pagamentos': {
      id: '/admin/dashboard/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/dashboard/pagamentos'
      preLoaderRoute: typeof AdminDashboardPagamentosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/pedidos': {
      id: '/admin/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/admin/dashboard/pedidos'
      preLoaderRoute: typeof AdminDashboardPedidosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/produtos': {
      id: '/admin/dashboard/produtos'
      path: '/produtos'
      fullPath: '/admin/dashboard/produtos'
      preLoaderRoute: typeof AdminDashboardProdutosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/resgates': {
      id: '/admin/dashboard/resgates'
      path: '/resgates'
      fullPath: '/admin/dashboard/resgates'
      preLoaderRoute: typeof AdminDashboardResgatesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/visao': {
      id: '/admin/dashboard/visao'
      path: '/visao'
      fullPath: '/admin/dashboard/visao'
      preLoaderRoute: typeof AdminDashboardVisaoRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/whatsapp': {
      id: '/admin/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/dashboard/whatsapp'
      preLoaderRoute: typeof AdminDashboardWhatsappRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/financeiro/dre': {
      id: '/admin/dashboard/financeiro/dre'
      path: '/dre'
      fullPath: '/admin/dashboard/financeiro/dre'
      preLoaderRoute: typeof AdminDashboardFinanceiroDreRouteImport
      parentRoute: typeof AdminDashboardFinanceiroRoute
    }
  }
}

interface AdminDashboardFinanceiroRouteChildren {
  AdminDashboardFinanceiroDreRoute: typeof AdminDashboardFinanceiroDreRoute
}

const AdminDashboardFinanceiroRouteChildren: AdminDashboardFinanceiroRouteChildren =
  {
    AdminDashboardFinanceiroDreRoute: AdminDashboardFinanceiroDreRoute,
  }

const AdminDashboardFinanceiroRouteWithChildren =
  AdminDashboardFinanceiroRoute._addFileChildren(
    AdminDashboardFinanceiroRouteChildren,
  )

interface AdminDashboardRouteChildren {
  AdminDashboardAuditoriaRoute: typeof AdminDashboardAuditoriaRoute
  AdminDashboardCardapioRoute: typeof AdminDashboardCardapioRoute
  AdminDashboardCategoriasRoute: typeof AdminDashboardCategoriasRoute
  AdminDashboardClientesRoute: typeof AdminDashboardClientesRoute
  AdminDashboardConfiguracoesRoute: typeof AdminDashboardConfiguracoesRoute
  AdminDashboardCuponsRoute: typeof AdminDashboardCuponsRoute
  AdminDashboardEntregasRoute: typeof AdminDashboardEntregasRoute
  AdminDashboardFinanceiroRoute: typeof AdminDashboardFinanceiroRouteWithChildren
  AdminDashboardGatewaysRoute: typeof AdminDashboardGatewaysRoute
  AdminDashboardHorariosRoute: typeof AdminDashboardHorariosRoute
  AdminDashboardLojaPremiosRoute: typeof AdminDashboardLojaPremiosRoute
  AdminDashboardPagamentosRoute: typeof AdminDashboardPagamentosRoute
  AdminDashboardPedidosRoute: typeof AdminDashboardPedidosRoute
  AdminDashboardProdutosRoute: typeof AdminDashboardProdutosRoute
  AdminDashboardResgatesRoute: typeof AdminDashboardResgatesRoute
  AdminDashboardVisaoRoute: typeof AdminDashboardVisaoRoute
  AdminDashboardWhatsappRoute: typeof AdminDashboardWhatsappRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardAuditoriaRoute: AdminDashboardAuditoriaRoute,
  AdminDashboardCardapioRoute: AdminDashboardCardapioRoute,
  AdminDashboardCategoriasRoute: AdminDashboardCategoriasRoute,
  AdminDashboardClientesRoute: AdminDashboardClientesRoute,
  AdminDashboardConfiguracoesRoute: AdminDashboardConfiguracoesRoute,
  AdminDashboardCuponsRoute: AdminDashboardCuponsRoute,
  AdminDashboardEntregasRoute: AdminDashboardEntregasRoute,
  AdminDashboardFinanceiroRoute: AdminDashboardFinanceiroRouteWithChildren,
  AdminDashboardGatewaysRoute: AdminDashboardGatewaysRoute,
  AdminDashboardHorariosRoute: AdminDashboardHorariosRoute,
  AdminDashboardLojaPremiosRoute: AdminDashboardLojaPremiosRoute,
  AdminDashboardPagamentosRoute: AdminDashboardPagamentosRoute,
  AdminDashboardPedidosRoute: AdminDashboardPedidosRoute,
  AdminDashboardProdutosRoute: AdminDashboardProdutosRoute,
  AdminDashboardResgatesRoute: AdminDashboardResgatesRoute,
  AdminDashboardVisaoRoute: AdminDashboardVisaoRoute,
  AdminDashboardWhatsappRoute: AdminDashboardWhatsappRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EnderecosRoute: EnderecosRoute,
  FuncionamentoRoute: FuncionamentoRoute,
  HistoricoRoute: HistoricoRoute,
  LojaRoute: LojaRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RastreioRoute: RastreioRoute,
  ResgatesRoute: ResgatesRoute,
  TermosRoute: TermosRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
