/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDashboardVisaoRouteImport } from './routes/admin.dashboard.visao'
import { Route as AdminDashboardProdutosRouteImport } from './routes/admin.dashboard.produtos'
import { Route as AdminDashboardPedidosRouteImport } from './routes/admin.dashboard.pedidos'
import { Route as AdminDashboardPagamentosRouteImport } from './routes/admin.dashboard.pagamentos'
import { Route as AdminDashboardHorariosRouteImport } from './routes/admin.dashboard.horarios'
import { Route as AdminDashboardFinanceiroRouteImport } from './routes/admin.dashboard.financeiro'
import { Route as AdminDashboardCategoriasRouteImport } from './routes/admin.dashboard.categorias'
import { Route as AdminDashboardAuditoriaRouteImport } from './routes/admin.dashboard.auditoria'
import { Route as AdminDashboardFinanceiroDreRouteImport } from './routes/admin.dashboard.financeiro.dre'

const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardVisaoRoute = AdminDashboardVisaoRouteImport.update({
  id: '/visao',
  path: '/visao',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardProdutosRoute = AdminDashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPedidosRoute = AdminDashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPagamentosRoute =
  AdminDashboardPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardHorariosRoute = AdminDashboardHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardFinanceiroRoute =
  AdminDashboardFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCategoriasRoute =
  AdminDashboardCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardAuditoriaRoute = AdminDashboardAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardFinanceiroDreRoute =
  AdminDashboardFinanceiroDreRouteImport.update({
    id: '/dre',
    path: '/dre',
    getParentRoute: () => AdminDashboardFinanceiroRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/auditoria': typeof AdminDashboardAuditoriaRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/financeiro': typeof AdminDashboardFinanceiroRouteWithChildren
  '/admin/dashboard/horarios': typeof AdminDashboardHorariosRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
  '/admin/dashboard/produtos': typeof AdminDashboardProdutosRoute
  '/admin/dashboard/visao': typeof AdminDashboardVisaoRoute
  '/admin/dashboard/financeiro/dre': typeof AdminDashboardFinanceiroDreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard/auditoria': typeof AdminDashboardAuditoriaRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/financeiro': typeof AdminDashboardFinanceiroRouteWithChildren
  '/admin/dashboard/horarios': typeof AdminDashboardHorariosRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
  '/admin/dashboard/produtos': typeof AdminDashboardProdutosRoute
  '/admin/dashboard/visao': typeof AdminDashboardVisaoRoute
  '/admin/dashboard/financeiro/dre': typeof AdminDashboardFinanceiroDreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/auditoria': typeof AdminDashboardAuditoriaRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/financeiro': typeof AdminDashboardFinanceiroRouteWithChildren
  '/admin/dashboard/horarios': typeof AdminDashboardHorariosRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
  '/admin/dashboard/produtos': typeof AdminDashboardProdutosRoute
  '/admin/dashboard/visao': typeof AdminDashboardVisaoRoute
  '/admin/dashboard/financeiro/dre': typeof AdminDashboardFinanceiroDreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/auditoria'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/financeiro'
    | '/admin/dashboard/horarios'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
    | '/admin/dashboard/produtos'
    | '/admin/dashboard/visao'
    | '/admin/dashboard/financeiro/dre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/dashboard/auditoria'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/financeiro'
    | '/admin/dashboard/horarios'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
    | '/admin/dashboard/produtos'
    | '/admin/dashboard/visao'
    | '/admin/dashboard/financeiro/dre'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/auditoria'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/financeiro'
    | '/admin/dashboard/horarios'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
    | '/admin/dashboard/produtos'
    | '/admin/dashboard/visao'
    | '/admin/dashboard/financeiro/dre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/visao': {
      id: '/admin/dashboard/visao'
      path: '/visao'
      fullPath: '/admin/dashboard/visao'
      preLoaderRoute: typeof AdminDashboardVisaoRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/produtos': {
      id: '/admin/dashboard/produtos'
      path: '/produtos'
      fullPath: '/admin/dashboard/produtos'
      preLoaderRoute: typeof AdminDashboardProdutosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/pedidos': {
      id: '/admin/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/admin/dashboard/pedidos'
      preLoaderRoute: typeof AdminDashboardPedidosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/pagamentos': {
      id: '/admin/dashboard/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/dashboard/pagamentos'
      preLoaderRoute: typeof AdminDashboardPagamentosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/horarios': {
      id: '/admin/dashboard/horarios'
      path: '/horarios'
      fullPath: '/admin/dashboard/horarios'
      preLoaderRoute: typeof AdminDashboardHorariosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/financeiro': {
      id: '/admin/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/admin/dashboard/financeiro'
      preLoaderRoute: typeof AdminDashboardFinanceiroRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/categorias': {
      id: '/admin/dashboard/categorias'
      path: '/categorias'
      fullPath: '/admin/dashboard/categorias'
      preLoaderRoute: typeof AdminDashboardCategoriasRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/auditoria': {
      id: '/admin/dashboard/auditoria'
      path: '/auditoria'
      fullPath: '/admin/dashboard/auditoria'
      preLoaderRoute: typeof AdminDashboardAuditoriaRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/financeiro/dre': {
      id: '/admin/dashboard/financeiro/dre'
      path: '/dre'
      fullPath: '/admin/dashboard/financeiro/dre'
      preLoaderRoute: typeof AdminDashboardFinanceiroDreRouteImport
      parentRoute: typeof AdminDashboardFinanceiroRoute
    }
  }
}

interface AdminDashboardFinanceiroRouteChildren {
  AdminDashboardFinanceiroDreRoute: typeof AdminDashboardFinanceiroDreRoute
}

const AdminDashboardFinanceiroRouteChildren: AdminDashboardFinanceiroRouteChildren =
  {
    AdminDashboardFinanceiroDreRoute: AdminDashboardFinanceiroDreRoute,
  }

const AdminDashboardFinanceiroRouteWithChildren =
  AdminDashboardFinanceiroRoute._addFileChildren(
    AdminDashboardFinanceiroRouteChildren,
  )

interface AdminDashboardRouteChildren {
  AdminDashboardAuditoriaRoute: typeof AdminDashboardAuditoriaRoute
  AdminDashboardCategoriasRoute: typeof AdminDashboardCategoriasRoute
  AdminDashboardFinanceiroRoute: typeof AdminDashboardFinanceiroRouteWithChildren
  AdminDashboardHorariosRoute: typeof AdminDashboardHorariosRoute
  AdminDashboardPagamentosRoute: typeof AdminDashboardPagamentosRoute
  AdminDashboardPedidosRoute: typeof AdminDashboardPedidosRoute
  AdminDashboardProdutosRoute: typeof AdminDashboardProdutosRoute
  AdminDashboardVisaoRoute: typeof AdminDashboardVisaoRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardAuditoriaRoute: AdminDashboardAuditoriaRoute,
  AdminDashboardCategoriasRoute: AdminDashboardCategoriasRoute,
  AdminDashboardFinanceiroRoute: AdminDashboardFinanceiroRouteWithChildren,
  AdminDashboardHorariosRoute: AdminDashboardHorariosRoute,
  AdminDashboardPagamentosRoute: AdminDashboardPagamentosRoute,
  AdminDashboardPedidosRoute: AdminDashboardPedidosRoute,
  AdminDashboardProdutosRoute: AdminDashboardProdutosRoute,
  AdminDashboardVisaoRoute: AdminDashboardVisaoRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
