/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDashboardPedidosRouteImport } from './routes/admin.dashboard.pedidos'
import { Route as AdminDashboardPagamentosRouteImport } from './routes/admin.dashboard.pagamentos'
import { Route as AdminDashboardCategoriasRouteImport } from './routes/admin.dashboard.categorias'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardPedidosRoute = AdminDashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPagamentosRoute =
  AdminDashboardPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCategoriasRoute =
  AdminDashboardCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/categorias': typeof AdminDashboardCategoriasRoute
  '/admin/dashboard/pagamentos': typeof AdminDashboardPagamentosRoute
  '/admin/dashboard/pedidos': typeof AdminDashboardPedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/categorias'
    | '/admin/dashboard/pagamentos'
    | '/admin/dashboard/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/pedidos': {
      id: '/admin/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/admin/dashboard/pedidos'
      preLoaderRoute: typeof AdminDashboardPedidosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/pagamentos': {
      id: '/admin/dashboard/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/dashboard/pagamentos'
      preLoaderRoute: typeof AdminDashboardPagamentosRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/categorias': {
      id: '/admin/dashboard/categorias'
      path: '/categorias'
      fullPath: '/admin/dashboard/categorias'
      preLoaderRoute: typeof AdminDashboardCategoriasRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardCategoriasRoute: typeof AdminDashboardCategoriasRoute
  AdminDashboardPagamentosRoute: typeof AdminDashboardPagamentosRoute
  AdminDashboardPedidosRoute: typeof AdminDashboardPedidosRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardCategoriasRoute: AdminDashboardCategoriasRoute,
  AdminDashboardPagamentosRoute: AdminDashboardPagamentosRoute,
  AdminDashboardPedidosRoute: AdminDashboardPedidosRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
